version: "3.7"

services:

  main:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - oronic

  nginx:
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./config/docker/nginx/:/etc/nginx/conf.d/
    ports:
      - ${API_PORT}:80
    networks:
      - oronic

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/backups
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    networks:
      - oronic

networks:
  oronic:
    driver: bridge
